### ISSUE TITLE
Braking changes

### ISSUE THREAD

**Issue by ram4nd** [Ocramius/PackageVersions#132] opened 2020-03-27 08:20 UTC
Releases after 1.5.1 require PHP 7.4. That may cause issues. In sentry there is dependency of this package and dependency loading requires version "^1.2.0". So since 1.7.0 was released sentry also requires PHP 7.4. The solution would be to release 1.7.0 and newer with new major release "2.0.0" since it has breaking changes for people with PHP 7.3.

I hope you get the issue from this description.

**Comment by Ocramius** [comment] 2020-03-27 08:34
Duplicate of #105

**Closed by Ocramius** 2020-03-27 08:34 UTC
