### ISSUE TITLE
Plugin installation failed

### ISSUE THREAD

**Issue by VincentLanglet** [Ocramius/PackageVersions#98] opened 2019-07-16 23:10 UTC
A friend started a project and get this error during the `composer install`.

![image](https://user-images.githubusercontent.com/9052536/61335097-8f6fb180-a82c-11e9-82d2-a6569d3b6402.png)

This is the repo to reproduce the bug:
https://github.com/ak3l/Cours_Symfony4/tree/bug

Instead following the actual README, do `composer install` without `--no-plugins --no-scripts` to get the error.

When I run `composer install -vv`, I get
```
 - Installing ocramius/package-versions (1.4.0): Reading /home/vagrant/.composer/cache/files/ocramius/package-versions/9015316288b55423c693c083934dccb5ab72981d.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/home/vagrant/code/vendor/ocramius/package-versions/200f6a66a0865848df9170ec0fd15921' -d '/home/vagrant/code/vendor/composer/f1785882'
Plugin installation failed, rolling back
```

**Comment by Ocramius** [comment] 2019-07-17 04:08
Duplicate of #97- please check that you aren't using mixed users when creating the `/home/vagrant/code/vendor` directory.

Operating with mixed `UID` on a linux system will indeed lead to files owned by separate users, and that will (by design) prevent separate users from editing each other's files unless they are in the same group and the files have group rights.

**Closed by Ocramius** 2019-07-17 04:08 UTC

**Comment by VincentLanglet** [comment] 2019-07-17 07:24
@Ocramius I dont have multiple user.
![image](https://user-images.githubusercontent.com/9052536/61355425-ae923180-a874-11e9-9372-08ef5a980521.png)

**Comment by Ocramius** [comment] 2019-07-17 07:27
Do you have a full trace for the error above?

**Comment by VincentLanglet** [comment] 2019-07-17 07:49
@Ocramius This is all I have:

![image](https://user-images.githubusercontent.com/9052536/61357252-2ada4400-a878-11e9-90d0-4057ca7699ce.png)

**Comment by Ocramius** [comment] 2019-07-17 07:53
And you run that with the `vagrant` user?

This is the second report of issues with homestead, so please report upstream on their end: something has been recently messed up there.

**Comment by VincentLanglet** [comment] 2019-07-17 08:02
Yes, I run `composer install` with the vagrant user.

I did report the issue on homestead too. But since I don't have knowledge about both vagrant & composer plugin, I wasn't sure if it was a homestead issue or an ocramius issue.

**Comment by Ocramius** [comment] 2019-07-17 08:03
From the trace above, there are files in there that aren't set up with the correct rights, so I suspect it's mostly a UID issue in how homestead runs CLI tasks.
