### ISSUE TITLE
Issue with installer.php

### ISSUE THREAD

**Issue by JoshuaCHolden** [Ocramius/PackageVersions#125] opened 2020-03-06 10:24 UTC
Hello, My apologies if the naming is incorrect this is the first issue I have raised on git hub, I am encountering the following error in my project when I try to composer install

Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34
ERROR: Service 'web' failed to build: The command '/bin/sh -c composer install -n --ansi --no-progress --no-suggest --ignore-platform-reqs --no-scripts --prefer-dist' returned a non-zero code: 255

I have tried with php versions 7.1, 7.2 and 7.3 with no luck, is this a known issue? it has only started happening recently

**Comment by Ocramius** [comment] 2020-03-06 10:26
Duplicate of #105 - please read entire thread.

**Closed by Ocramius** 2020-03-06 10:26 UTC

**Comment by Ocramius** [comment] 2020-03-06 10:29
BTW, your problem is `--ignore-platform-reqs` - don't ignore those ;-)

**Comment by JoshuaCHolden** [comment] 2020-03-06 11:50
Thank you so much for this! Much appreciated this fixed my issue
