### ISSUE TITLE
Plugin ocramius/package-versions could not be initialized, class not found: PackageVersions\Installer

### ISSUE THREAD

**Issue by markdza** [Ocramius/PackageVersions#97] opened 2019-07-11 15:52 UTC
Tried to install another package which has a dependency on this one. When it tried to install it the following error came up

```
[UnexpectedValueException]
  Plugin ocramius/package-versions could not be initialized, class not found: PackageVersions\Installer
```

Also tried to do a direct install of this package by `$ composer require ocramius/package-versions`. Same error

Happened inside the Homestead v8 box (Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64))

**Comment by Ocramius** [comment] 2019-07-11 15:59
I'd need steps to reproduce this problem

**Comment by markdza** [comment] 2019-07-11 17:46
Steps:

1. On a windows 7 machine install latest versions of:
- https://www.vagrantup.com
- https://www.virtualbox.org

2. Set up Homestead v8 - https://laravel.com/docs/5.8/homestead

3. Set up a new Laravel project

4. Do `composer install` (I did `composer install -vvv` for below trace)

5. Error might show up (I'm not sure as I am already using an existing Laravel project)

```
  - Installing ocramius/package-versions (1.4.0): Reading /home/vagrant/.composer/cache/files/ocramius/package-versions/9015316288b55423c693c083934dccb5ab72981d.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/home/vagrant/projects/pegasus/vendor/ocramius/package-versions/b465f27dd1125b7d9af26e94cdbda044' -d '/home/vagrant/projects/pegasus/vendor/composer/753d3c1d'
Plugin installation failed, rolling back
  - Removing ocramius/package-versions (1.4.0)


  [UnexpectedValueException]
  Plugin ocramius/package-versions could not be initialized, class not found: PackageVersions\Installer


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:208
 Composer\Plugin\PluginManager->registerPackage() at phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php:62
 Composer\Installer\PluginInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:595
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:229
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:122
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24
```

**Comment by Ocramius** [comment] 2019-07-11 18:04
Closing here then: this is to be pushed into the homestead issue tracker first, as it seems to be a filesystem issue first (we discussed it in private via mail), and not of this project per-se.

As previously discussed in private, I believe that the homestead/vagrant setup may be using mixed `UID` depending on which operation is being performed.

**Closed by Ocramius** 2019-07-11 18:04 UTC
Labels: bug, missing tests

**Comment by svpernova09** [comment] 2019-07-18 13:55
Hi @Ocramius!

> As previously discussed in private, I believe that the homestead/vagrant setup may be using mixed UID depending on which operation is being performed.

Can you elaborate? Is this referring to the UID of the `vagrant` user in the VM?

(please feel free to ping me for Homestead questions, always happy to help rule out possibilities)

**Comment by Ocramius** [comment] 2019-07-18 17:52
See also #98

**Comment by svpernova09** [comment] 2019-07-18 18:04
Thanks, I've been working through @VincentLanglet's Homestead issue (https://github.com/laravel/homestead/issues/1240) and have narrowed it down to be a specific Virtualbox bug (Issue doesn't appear with other providers, specifically Parallels so far). 

In my own testing I'm running into the issue where composer goes to unzip the folder that was downloaded I get the message `caution: not extracting; -d ignored` Which then is causing the `Plugin ocramius/package-versions could not be initialized, class not found: PackageVersions\Installer` error because the archive isn't unzipped. 

Here's the specific issue I'm seeing (https://github.com/laravel/homestead/issues/1240#issuecomment-512658688) I know this isn't an issue with your code, but do you have any insights in what might be causing the `unzip` command to fail? I'm using a modified composer with some extra debugging for my own sake for tracing why the class isn't found.

This is the unzip command that's being run:

```
unzip -vvv  '/Users/halo/Code/Cours_Symfony4/symfony4/vendor/ocramius/package-versions/811721dfca1c665ca0b903337a20b474' -d '/Users/halo/Code/Cours_Symfony4/symfony4/vendor/composer/98742ed8'
```

But the path`/Users/halo/Code/Cours_Symfony4/symfony4/vendor/ocramius/package-versions/811721dfca1c665ca0b903337a20b474` looks odd to me,  shouldn't that be a `.zip` file instead of a folder?

**Comment by Ocramius** [comment] 2019-07-18 18:10
> but do you have any insights in what might be causing the `unzip` to fail?

Not really: there is one specific code location generated by package-versions`, which is `vendor/ocramius/package-versions/src/PackageVersions/Versions.php`

The file is written by following code:

https://github.com/Ocramius/PackageVersions/blob/1d32342b8c1eb27353c8887c366147b4c2da673c/src/PackageVersions/Installer.php#L148-L151
