### ISSUE TITLE
'private static string' in installer.php

### ISSUE THREAD

**Issue by necmettin** [Ocramius/PackageVersions#137] opened 2020-04-08 04:49 UTC
Is this not an error? Am I missing something?

`private static string $generatedClassTemplate = <<<'PHP'`

And the error message:
`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33`

**Comment by Ocramius** [comment] 2020-04-08 10:20
Duplicate of #105 

BTW, indeed, it could be a `private const` :+1:

**Closed** 2020-04-08 10:20 UTC
Labels: duplicate

**Comment by NiklasBr** [comment] 2020-05-16 13:26
My composer requires looks like this:

```
  "require": {
    "php": ">=7.2",
    "ocramius/package-versions": "^1.2",
```

And now I get the same error as above:

```sh
niklas@Fractal:~/workspace/pimcore-dev$ php -v
PHP 7.2.24-0ubuntu0.18.04.4 (cli) (built: Apr  8 2020 15:45:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.4, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
niklas@Fractal:~/workspace/pimcore-dev$ composer update
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/niklas/workspace/pimcore-dev/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33

Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/niklas/workspace/pimcore-dev/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 33
```

Please consider being more kind to us ancient PHP 7.2 users!

**Comment by Ocramius** [comment] 2020-05-16 13:28
please read the thread in #105, @NiklasBr: you probably aren't using `composer update` as you should.

**Comment by NiklasBr** [comment] 2020-05-16 13:48
I did. I'm just asking to play nice with PHP 7.2 -- a version which is still actively supported and updated. _Your repository. Your rules. One hundred percent._ But really, using `composer update` is not the correct way to update Composer dependencies according to you?

**Comment by Ocramius** [comment] 2020-05-16 13:49
not if you run the `composer update` on a system that isn't production-alike: I described that in the referenced issue, and you will be bitten again by it if you don't fix that.

**Comment by NiklasBr** [comment] 2020-05-16 13:55
It was simple to resolve, I hope you can accept my PR.

**Comment by necmettin** [comment] 2020-05-16 13:58
I know we don’t get a say in this but please make the code php7.2 compatible. This could easily be avoided by removing a single word, which changes nothing end-result-wise.

**Comment by Ocramius** [comment] 2020-05-16 14:03
hey there, the code requires PHP 7.4, and that's the end of the story.

**Comment by Ocramius** [comment] 2020-05-16 14:10
BTW, there are stable releases that support even older PHP 7.x  versions.
