### ISSUE TITLE
v1.5.0 release does not follow semver

### ISSUE THREAD

**Issue by DivineOmega** [Ocramius/PackageVersions#108] opened 2019-09-26 08:27 UTC
PackageVersions v1.5.0 dropped support for PHP 7.2. This is a breaking change and based on semver this should have been released as v2.0.0.

This is causing issues upgrading packages when running on lower PHP versions.

Example of the issue:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for ocramius/package-versions 1.5.1 -> satisfiable by ocramius/package-versions[1.5.1].
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.15) does not satisfy that requirement.
  Problem 2
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - jean85/pretty-package-versions 1.2 requires ocramius/package-versions ^1.2.0 -> satisfiable by ocramius/package-versions[1.5.1].
    - Installation request for jean85/pretty-package-versions 1.2 -> satisfiable by jean85/pretty-package-versions[1.2].
```

**Comment by DivineOmega** [comment] 2019-09-26 08:30
Please do correct me if I'm wrong. I realise I may be missing something here.

**Comment by Ocramius** [comment] 2019-09-26 08:35
Duplicate of https://github.com/Ocramius/PackageVersions/issues/105

Besides, bumping dependencies is not a BC break (not even in semver)

**Closed by Ocramius** 2019-09-26 08:35 UTC

**Comment by DivineOmega** [comment] 2019-09-26 08:48
@Ocramius Thanks for referencing the duplicate issue. The links within in have increased my understand of this issue now. :+1:

**Comment by Ocramius** [comment] 2019-09-26 08:51
@DivineOmega thanks for taking the time to read them: please spread the good word :+1:

**Comment by spider-mane** [comment] 2019-12-12 22:59
I read the issue thread referenced and still I don't get your rationale on bumping versions in your composer.json. According to the official composer documentation:

 "`require` and `require-dev` also support references to specific PHP versions and PHP extensions your project needs to run successfully." 

The way you explain it, you bumped the version essentially to dictate the version of php you think the end user should be running, or more generously, simply because at the time it was the latest version of php, which is clearly at odds with the purpose of composer version constraints.

There's no reason for this package to set a minimum php requirement of 7.3. I ran your tests on 5.6 and up and they pass at 7.2. It's even likely that it's fully compatible with 7.1, as a syntax check found no issues, but the test suite requires a minimum of php 7.2. to run.

I get that running into conflicts is avoidable, but again, your reasoning for requiring php 7.3 seems deeply flawed.

**Comment by Ocramius** [comment] 2019-12-12 23:09
You are free to use older versions of the package, but I bump minimum versions for a number of reasons:

 1. I try to support only what I'm willing to install myself
 2. I do want to push the community forward
 3. I reduce the matrix of supported dependency permutations
 4. I reduce the number of tested dependency permutations
 5. I do like to play with newer shinier dependencies (and if I don't bump, I often can't)
 6. I do develop this stuff for fun before duty
 7. I sensibilise the community towards maintenance effort: you are getting something for free, yet you are here asking to do more than what I'm willing to do (and that's OK until you realise this)

I'm generally going to bump minimum version to "current stable" in all my packages when releasing new minor versions, and I configured @dependabot to bump all dependencies it can bump as well.

**Comment by spider-mane** [comment] 2019-12-13 00:00
My apologies if I came across harshly, I'm not asking you to do anything your not willing to do, it's entirely up to you. I was only making a suggestion, and trying to provide as detailed an explanation for that suggestion as I can. I agree that pushing the community forward is important. This is just the first time I've encountered a php version constraint being set specifically for that purpose. I appreciate your contributions, and I was able to resolve the issue I had that led me here by heeding a suggestion you gave in the other thread, but was still perplexed by the decision to upgrade. However, in all that, learned a valuable lesson on why I shouldn't run composer on a local installation of php for a project being developed in a vm, so perhaps you're onto something lol

**Comment by Ocramius** [comment] 2019-12-13 11:33
> However, in all that, learned a valuable lesson on why I shouldn't run composer on a local installation of php for a project being developed in a vm, so perhaps you're onto something lol

I know it feels like a kick in the teeth, but I had a lot of people learning how `composer update` works through my packages :D
