### ISSUE TITLE
Change the chmod call to @chmod

### ISSUE THREAD

**Issue by jeremy-smith-maco** [Ocramius/PackageVersions#63] opened 2018-03-29 07:06 UTC
https://github.com/Ocramius/PackageVersions/blob/4489d5002c49d55576fa0ba786f42dbb009be46f/src/PackageVersions/Installer.php#L122

Change this from `chmod()` to `@chmod()`

**Comment by Ocramius** [comment] 2018-03-29 12:25
Duplicate of https://github.com/Ocramius/PackageVersions/pull/47

**Closed by Ocramius** 2018-03-29 12:25 UTC
