### ISSUE TITLE
PHP 5 compatibility

### ISSUE THREAD

**Issue by bartfeenstra** [Ocramius/PackageVersions#24] opened 2016-06-23 13:26 UTC
Hi! I'm here on behalf of Drupal, where we need functionality like this package provides. At this point we're pledged to support PHP 5.5, but we will increase the minimum requirement to PHP 5.6 later this year together with upgrading our Symfony components to ~3.0. PHP 7 is supported, but this is a matter of minimum requirements.

We've done a quick review of the code and it looks like the only thing preventing PHP 5 compatibility are the return type hints. Will you accept a PR that introduces this compatibility, or do you suggest we fork the project for that purpose?

Thanks!

**Comment by Ocramius** [comment] 2016-06-23 16:06
Hello,

PHP 5.x support is not gonna get into this package, sorry.

Please upgrade PHP requirements on your side, if you really need it. Please consider forking the project if you wish to maintain 5.x compatibility.

Closing as duplicate of #10

**Closed by Ocramius** 2016-06-23 16:06 UTC
Labels: duplicate, question, wontfix
