### ISSUE TITLE
v1.7.0 PHP Parse error Installer.php on line 34

### ISSUE THREAD

**Issue by abarke** [Ocramius/PackageVersions#126] opened 2020-03-06 12:48 UTC
$ composer update

Installing ocramius/package-versions (1.7.0): Cloning 651c372efc from cache

PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ...\vendor\ocramius\package-versions\src\PackageVersions\Installer.php on line 34

**Comment by Ocramius** [comment] 2020-03-06 12:49
Duplicate of #105: please read the full thread

**Closed by Ocramius** 2020-03-06 12:49 UTC
