### ISSUE TITLE
PHP Parse error in ocramius/package-versions (1.6.0)

### ISSUE THREAD

**Issue by ItayPodhajcer** [Ocramius/PackageVersions#121] opened 2020-03-05 11:53 UTC
Hi,

Just ran an automated build which runs composer as part of the pipeline and got the following error:

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /soruce/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34`

Compsoer was trying to install `ocramius/package-versions` version 1.6.0 when the error occured.

**Comment by Ocramius** [comment] 2020-03-05 11:56
Duplicate of #105 - see https://github.com/Ocramius/PackageVersions/issues/105#issuecomment-516617164

**Closed by Ocramius** 2020-03-05 11:56 UTC
