### ISSUE TITLE
Parse error: syntax error, unexpected 'string' (T_STRING)

### ISSUE THREAD

**Issue by moeinpaki** [Ocramius/PackageVersions#129] opened 2020-03-09 07:53 UTC
Hi there,

I get this error from 3 days ago on the composer install

Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in app/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34

**Comment by kmgalanakis** [comment] 2020-03-09 07:55
Same here!

**Comment by Ocramius** [comment] 2020-03-09 08:08
Duplicate of #105

**Closed by Ocramius** 2020-03-09 08:08 UTC

**Comment by moeinpaki** [comment] 2020-03-09 08:38
my PHP version

PHP 7.3.11 (cli) (built: Dec 13 2019 19:21:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

is there any other thing wrong with that?

**Comment by Ocramius** [comment] 2020-03-09 08:42
Yes: this package requires PHP 7.4.

If you want to use PHP 7.3, you need o rely on version 1.5.* of this package (which supported PHP 7.3)
